pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-token',
                    url: 'https://github.com/makhmudovs1/OrderFlow.git'
            }
        }
        stage('Build Backend') {
            steps {
                dir('orderflow-backend') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Test Backend') {
            steps {
                dir('orderflow-backend') {
                    sh 'mvn test'
                }
            }
        }
        stage('SonarQube') {
            steps {
                dir('orderflow-backend') {
                    withSonarQubeEnv('SonarQube') {
                        withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_AUTH_TOKEN')]) {
                            sh 'mvn sonar:sonar -Dsonar.login=${SONAR_AUTH_TOKEN}'
                        }
                    }
                }
            }
        }
        stage('Generate Allure Report') {
            steps {
                dir('orderflow-backend') {
                    sh 'mvn allure:report'
                }
                allure includeProperties: false, jdk: '', results: [[path: '**/allure-results']]
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('orderflow-backend') {
                    sh 'docker build -t maftuna09/my-app:latest .'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh """
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        docker push maftuna09/my-app:latest
                    """
                }
            }
        }
    }
}